Ftr 3901 message search updated
otavanopisto/muikku pull request #5195
Opened 2020-11-23 08:59 UTC by saaralepisto

Indexes must drop and re-index

2020-11-25 13:28 UTC, anttiviljakainen requested changes

2020-11-25 13:28 UTC, anttiviljakainen commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
> +      for(CommunicatorMessage message : communicatorMessages) {
Probably enough to just index the single message from recipient.getCommunicatorMessage()

2020-11-25 13:28 UTC, anttiviljakainen commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
> +          if (isLogged.equals(Boolean.TRUE) && archivedBySender.equals(Boolean.TRUE)) {
archived should probably be filtered in the search so that the indexing doesn't break

2020-11-25 13:28 UTC, anttiviljakainen commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
> +          List<IndexedCommunicatorMessageRecipient> receiverList = result.getReceiver();
Recipientlist likely needs to be filtered and not constructed from the indexed data

2020-11-25 13:28 UTC, anttiviljakainen commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
> +          return Response.noContent().build();
Return empty list instead of noContent i.e. just ignore this check.

2020-11-25 13:28 UTC, anttiviljakainen commented on muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
> +          e.printStackTrace();
Clean up exception handling

2020-12-07 08:33 UTC, anttiviljakainen commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorSearchResultRESTModel.java
> +  private Boolean readByreceiver;
Naming is maybe bit confusing but it's there to mark if the message is read by the user requesting the search list.

2020-12-07 09:43 UTC, jjlankinen commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorSearchResultRESTModel.java
> +  private Boolean readByreceiver;
Maybe use full camelCase a.k.a readByReceiver?

2020-12-10 12:06 UTC, pkukkon requested changes

2020-12-10 12:06 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_fi.properties
> +plugin.communicator.notification.newmessage.mail.subject = Uusi viesti Muikussa
More entries than in the English bundle? Should be equal.

2020-12-10 12:06 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/CommunicatorMessageIndexer.java
> +      logger.warning(String.format("could not index message #%s/%s//%s", indexedCommunicatorMessage.getClass().getSimpleName(), indexedCommunicatorMessage.getId(), e));
Exception to string might not be informative enough? Maybe logger.log(Level.WARNING, "msg", e); instead?

2020-12-14 07:08 UTC, pkukkon approved these changes

2020-12-17 10:12 UTC, pkukkon approved these changes

2021-01-22 12:12 UTC, pkukkon submitted a review, later dismissed

2021-02-01 11:13 UTC, pkukkon approved these changes

2021-02-01 12:12 UTC, onzag approved these changes

2021-02-01 12:12 UTC, merged