Adding student councelot information for student
otavanopisto/muikku pull request #5240
Opened 2020-12-18 13:15 UTC by jjlankinen

Closes #5236

2021-01-07 16:38 UTC, onzag submitted a review, later dismissed
Don't see any problems

2021-01-18 06:25 UTC, pkukkon requested changes

2021-01-18 06:25 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/summary.ts
> +            result.forEach(function (studentsStudentCouncelor: any) {
The result set could probably be sorted by last name so the names wouldn't be in random order in the UI.

2021-01-18 06:25 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
> +                  let displayVacationPeroid = !!councelor.properties['profile-vacation-start'];
displayVacationPeriod

2021-01-18 06:25 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java
> +        return Response.status(Status.NOT_FOUND).build();
Shouldn't this be Status.FORBIDDEN instead?

2021-01-18 08:09 UTC, pkukkon approved these changes

2021-01-18 09:55 UTC, merged