5353 organization usergroup listing
otavanopisto/muikku pull request #5385
Opened 2021-03-15 13:50 UTC by avukkonen

closes #5353
closes #5283 
closes #5282

2021-03-22 07:03 UTC, onzag approved these changes

2021-03-22 07:40 UTC, jjlankinen requested changes

2021-03-22 07:40 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/new-usergroup.tsx
> +        return <DialogRow>
This should be replaced with `<form>` element as it wraps other form elements.

2021-04-12 05:41 UTC, onzag submitted a review, later dismissed

2021-04-12 05:46 UTC, jjlankinen submitted a review, later dismissed

2021-04-12 12:15 UTC, jjlankinen approved these changes

2021-04-12 12:15 UTC, merged