Teachers work list
otavanopisto/muikku pull request #5419
Opened 2021-04-07 05:34 UTC by jjlankinen

Closes #5391

2021-04-08 11:14 UTC, avukkonen requested changes

2021-04-08 11:14 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/work-list.tsx
>    public render() {
Why is this render method public?

2021-04-09 05:20 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/hops_readable.tsx
> +          <span className="application-sub-panel__item-data-single-entry">
Probably not needed, however the `span` element itself was used for styling in relative manner already. Styling that's attached to the span element is specific and only applies to that markup.

I could change the styling so it's not nested anymore and therefore the className could be changed as suggested.

2021-04-13 07:53 UTC, avukkonen approved these changes

2021-04-14 05:55 UTC, merged