Sticky search bar gab and content aligning fixed:
otavanopisto/muikku pull request #5430
Opened 2021-04-12 07:54 UTC by TeroOtavia

- application-panel-body.tsx
- Scroll event listener enabled in all device sizes, needed because it
  calculates wheter action bar is sticky or not
- OnScroll listener also calculates everytime offsetElementAgainstTop,
  this fixes gab between action bar and header
- It is possible that this fixes may cause some other bugs, atleast none
  was found when I tested.
- Contains also some very minor code cleaning (const and let variable etc.)

Resolves #5421

2021-04-16 06:48 UTC, jjlankinen requested changes

2021-04-16 06:48 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-panel.scss
> +    position: sticky;
It seems we have 2 position properties. Wonder why Hound did not catch this. Also if `position: sticky` is the one to be used it needs to be placed before `right` property as they need to be placed in alphabetical order.

2021-04-16 06:48 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-panel.scss
> +  position: fixed;
`position` property needs to be placed before `right` property. Hound should have spotted this as properties order needs to be alphabetical.

2021-04-19 08:48 UTC, TeroOtavia commented
Issue is closed because currently this up coming fix would break logic with previously fixed scrolling issue in application-panel. They both use same properties to fix different thing different way that would collide together.

2021-04-19 08:50 UTC, TeroOtavia commented
Issue is closed because currently this up coming fix would break logic with previously fixed scrolling issue in application-panel. They both use same properties to fix different thing different way that would collide together.

2021-04-19 08:50 UTC, closed without merging