Discussion subreplies can be now hide/show with minus/plus icon button:
otavanopisto/muikku pull request #5474
Opened 2021-04-27 06:49 UTC by TeroOtavia

Discussion subreplies can be now hide/show with minus/plus icon button:
- current-thread.tsx
- threads.tsx
- application-list.scss

Contains also small bug fix that address this pin lock icon align problem

Resolves #1937

2021-04-29 09:57 UTC, avukkonen requested changes

2021-04-29 09:57 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx
> +                }</span>
why do we need reply.childReplyCount > 0 check inside the method here?

2021-05-11 11:03 UTC, avukkonen submitted a review, later dismissed

2021-05-12 10:45 UTC, jjlankinen approved these changes

2021-05-12 10:45 UTC, merged