5514 menu component refactoring to use list tag
otavanopisto/muikku pull request #5520
Opened 2021-05-17 07:51 UTC by TeroOtavia

Menu component now uses ul and li tags allover including menu-extra and its items items

2021-05-17 10:02 UTC, avukkonen requested changes

2021-05-17 10:02 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navigation.tsx
> +        {this.props.name ? (
classmModifier should always contain "menu-items--"

2021-05-17 10:02 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navigation.tsx
> +      <li className="menu__item--extra">
http://getbem.com/naming/

2021-05-17 11:15 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navbar/menu.tsx
> +          {this.props.navigation && this.props.navigation}
Does not matter. Its is always react jsx.element anyway. Whether it is array or single element works same way.

2021-09-24 11:02 UTC, avukkonen approved these changes

2021-09-24 11:08 UTC, merged