Organization overview - contact person
otavanopisto/muikku pull request #5613
Opened 2021-06-10 09:42 UTC by saaralepisto

closes #5577

2021-06-10 09:43 UTC, saaralepisto commented
https://github.com/otavanopisto/pyramus/pull/1272

2021-06-10 11:32 UTC, aviljakaine requested changes

2021-06-10 11:32 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java
> +    BridgeResponse<List<OrganizationContactPerson>> response = userSchoolDataController.listOrganizationContactPersons(dataSource, organization.getId());
`organization.getId()` returns OrganizationEntity's id in Muikku's database and it simply cannot be correct here (used as Pyramus' organization.id), pass organization's SchoolDataIdentifier's identifier string instead here.

2021-06-10 11:32 UTC, aviljakaine commented on muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
> +  public BridgeResponse<List<OrganizationContactPerson>> listOrganizationContactPersonsByOrganization(Long organizationId);
Change this to take in `String organizationIdentifier` which is Organization's SchoolDataIdentifier's identifier (string) instead. SchoolDataBridge's are expected to do the conversion from this identifier to the underlying system's format instead.

2021-06-10 11:32 UTC, aviljakaine commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +      Long organizationId) {
This will change into `String organizationIdentifier` so turn the identifier string into Pyramus' organizationId using `identifierMapper`.

2021-06-10 11:32 UTC, aviljakaine commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +      contactPersons = new ArrayList<>();
Is the loop needed here or could the original list just be passed on? I'm not sure about it, probably need to find similar calls and inspect if it's been used or not.

2021-06-11 08:13 UTC, aviljakaine requested changes

2021-06-14 05:19 UTC, merged