Some fine tuning for tabs
otavanopisto/muikku pull request #5838
Opened 2021-11-04 06:53 UTC by avukkonen

Tekee tabitoiminnallisuudesta paremmin yhteensopivan uuden opinnot- ja ohjaamonäkymän kanssa

Esim. aiemmin onTabChange() ammuttiin pelkästään tabin klikkaukselle, nyt se tehdään myös swipella

2021-11-18 06:01 UTC, jjlankinen submitted a review, later dismissed

2021-11-18 09:50 UTC, TeroOtavia requested changes

2021-11-18 09:50 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
> +
Same function is already imported from helper-functions.

2021-11-18 09:50 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
> +  let prevSlide = allTabs[allTabs.indexOf(activeTab) - 1];
No need to use `let`as variable is not changed before actual using. Use `const` instead.

2021-12-01 11:04 UTC, TeroOtavia approved these changes

2021-12-01 11:21 UTC, merged