5841 piilotettu materiaalisivu arvioinnissa
otavanopisto/muikku pull request #5898
Opened 2021-12-21 08:24 UTC by TeroOtavia

Hidden materials are now correctly shown at following places if student has answered material excercise before it was set to hidden:
- evaluation tool
- materials
- student records

Contains few new translations and styling changes for hidden material to indicate previously mentioned changes.

Resolves: #5841

2021-12-23 10:16 UTC, pkukkon requested changes

2021-12-23 10:16 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties
> +plugin.evaluation.evaluationModal.assignmentHiddenButAnswered = T�m� arvioitava teht�v� on piilotettu ja korvattu uudella teht�v�ll� mutta opiskelija on kerennyt siihen vastaamaan.
Molemmissa "...mutta opiskelija ehti jo vastaamaan siihen."

2021-12-23 10:16 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
> +plugin.workspace.materials.exerciseHiddenButAnswered = T�m� harjoutusteht�v� on piilotettu ja korvattu toisella teht�v�ll�. Olet kuitenkin kerennyt vastaamaan t�h�n teht�v��n jolloin opettaja my�s n�
harjoutustehtävä -> harjoitustehtävä

Molemmissa "Olet kuitenkin ehtinyt vastaamaan tähän tehtävään, joten opettaja näkee yhä vastauksesi ja voi sen arvioida."

2021-12-23 12:13 UTC, avukkonen approved these changes

2021-12-27 08:35 UTC, pkukkon approved these changes

2021-12-27 08:35 UTC, merged