Ceepos integration
otavanopisto/muikku pull request #5931
Opened 2022-01-05 07:30 UTC by pkukkon

2022-01-11 04:56 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfileJsPluginMessages_fi.properties
> +plugin.profile.purchases.addedEntries = Merkinn�t
That should not have been there in the first place as it was unused and left over line.

2022-01-11 06:23 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +    schoolDataBridgeSessionController.startSystemSession();
In Pyramus, endpoint permission is only given to trusted system.

2022-01-14 11:01 UTC, avukkonen requested changes

2022-01-14 11:01 UTC, TeroOtavia requested changes

2022-01-17 11:41 UTC, TeroOtavia approved these changes

2022-01-19 06:23 UTC, avukkonen approved these changes

2022-01-19 09:58 UTC, merged