Study programme & curriculum to whoami
otavanopisto/muikku pull request #5941
Opened 2022-01-17 05:12 UTC by saaralepisto

Closes #5938

2022-02-02 09:54 UTC, pkukkon requested changes

2022-02-02 09:54 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +    if (user.getCurriculumIdentifier() != null) {
If user is null, the code will crash here.

2022-02-02 09:54 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +    SchoolDataIdentifier curriculumId = SchoolDataIdentifier.fromId(user.getCurriculumIdentifier());
Proper indentation

2022-02-02 09:54 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +    Curriculum curriculum = user == null ? null : courseMetaController.findCurriculum(curriculumId.getDataSource(), curriculumId.getIdentifier());
user cannot be null at this point; the code would already have crashed before.

2022-02-02 09:54 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +    curriculumName = curriculum.getName();
If findCurriculum would return null, the code would crash at this point.

2022-02-04 06:04 UTC, pkukkon approved these changes

2022-02-04 10:29 UTC, jjlankinen approved these changes
This has been tested locally on 3 different occasions and has been approved earlier.

2022-02-04 10:29 UTC, merged