5808 yhdistelmaopintojaksot
otavanopisto/muikku pull request #6026
Opened 2022-02-24 11:09 UTC by aviljakaine

Closes #5808

2022-05-04 21:01 UTC, onzag submitted a review, later dismissed

2022-05-11 06:40 UTC, pkukkon commented on updates_devel/220321_supplementationrequest_workspacesubject.xml
> +<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
Remember to change to official database version.

2022-05-11 06:40 UTC, pkukkon commented on updates_devel/220321_supplementationrequest_workspacesubject.xml
> +<update xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ofw.fi/xml/2011/java-xmldb-updater/UpdaterSchema.xsd">
Remember to change to official database version.

2022-05-11 07:54 UTC, pkukkon approved these changes
Backend OK (with updated db script)

2022-05-12 06:10 UTC, avukkonen requested changes

2022-05-16 09:52 UTC, pkukkon approved these changes
Backend OK

2022-05-16 10:00 UTC, avukkonen submitted a review, later dismissed

2022-05-18 11:48 UTC, pkukkon approved these changes

2022-05-19 06:09 UTC, merged