Yhteydenottotiedot ohjaamoon
otavanopisto/muikku pull request #6054
Opened 2022-03-16 09:38 UTC by saaralepisto

Closes #6035

2022-03-16 09:43 UTC, saaralepisto commented
https://github.com/otavanopisto/pyramus/pull/1352

2022-03-21 11:05 UTC, pkukkon requested changes

2022-03-21 11:05 UTC, pkukkon commented on muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
> +    // Query that checks activity based on user having a study end date set
This comment doesn't relate to this method at all?

2022-04-14 06:41 UTC, pkukkon requested changes

2022-04-14 06:41 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +    return pyramusClient.responsePost(String.format("/students/students/%d/contactLogEntries", studentId), Entity.entity(payload, MediaType.APPLICATION_JSON), StudentContactLogEntryRestModel.class);
The creatorId in all response objects (contact log entries and their comments) are ids of the users in Pyramus. Before handing the response over to Muikku front-end, they should be converted to ids of the users in Muikku (i.e. userEntityId). Something like...

```
if (response.getEntity() != null && response.getEntity().getCreatorId() != null) {
  SchoolDataIdentifier identifier = identifierMapper.getStaffIdentifier(response.getEntity().getCreatorId());
  if (identifier != null) {
    UserSchoolDataIdentifier usdi = userSchoolDataIdentifierController.findUserSchoolDataIdentifierBySchoolDataIdentifier(identifier);
    if (usdi != null) {
      response.getEntity.setCreatorId(usdi.getUserEntity.getId());
    }
    else {
      // TODO log warning
      response.getEntity.setCreatorId(null);
    }
  }
  else {
    // TODO log warning
    response.getEntity.setCreatorId(null);
  }
}
// TODO Do the same with comments
```

Naturally this applies to all methods returning contact log entries and/or their comments.

2022-04-14 07:47 UTC, pkukkon requested changes

2022-04-14 07:47 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +  @RESTPermit (handling = Handling.INLINE, requireLoggedIn = true)
No permission handling within the method at all. Perhaps...

`@RESTPermit (GuiderPermissions.ACCESS_CONTACT_LOG)`

...given to all staff roles. Same with all the other endpoints dealing with contact log entries.

2022-04-14 07:47 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    BridgeResponse<StudentContactLogEntryRestModel> response = userSchoolDataController.updateStudentContactLogEntry(dataSource, userEntity.defaultSchoolDataIdentifier(), contactLogEntryId, payload);
Extra safety by checking that the creatorId in the payload object is that of the logged in user?

2022-04-14 07:47 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    BridgeResponse<StudentContactLogEntryCommentRestModel> response = userSchoolDataController.updateStudentContactLogEntryComment(dataSource, userEntity.defaultSchoolDataIdentifier(), entryId, comme
Same as when updating a contact log entry; check that the creatorId in payload is the same as the id of the currently logged in user.

2022-04-14 11:22 UTC, pkukkon approved these changes

2022-05-02 08:34 UTC, pkukkon approved these changes

2022-05-02 09:08 UTC, aviljakaine approved these changes

2022-05-02 10:14 UTC, merged