Added REST method increaseStudyTime
otavanopisto/muikku pull request #6063
Opened 2022-03-22 11:08 UTC by saaralepisto

Closes #6060

2022-03-23 08:12 UTC, pkukkon requested changes

2022-03-23 08:12 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +  @RESTPermit (handling = Handling.INLINE, requireLoggedIn = true)
Where will this endpoint even be used? Only checks that the user is logged in, so basically anyone could call it and add study time for anyone? Access definitely needs to be more limited.

2022-05-03 06:39 UTC, saaralepisto commented
https://github.com/otavanopisto/pyramus/pull/1371

2022-05-04 07:35 UTC, pkukkon approved these changes

2022-05-04 07:35 UTC, merged