6021 remade pullrequest
otavanopisto/muikku pull request #6078
Opened 2022-03-29 08:47 UTC by avukkonen

2022-03-30 08:03 UTC, TeroOtavia requested changes

2022-03-30 08:03 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/calendar.ts
> +  switch (action.type) {
You can simplify and make it more easier to read with following changes if you wish. At least consider

```ts
const initialState: Calendar = {

  state: "LOADING",

  guidanceEvents: [],

};



/**

 * Reducer function for calendar

 *

 * @param reducerState reducerState

 * @param action action

 * @returns returns state

 */

export const calendarReducer = (

  reducerState = initialState,

  action: ActionType

) => {

  switch (action.type) {

    case "UPDATE_CALENDAR_EVENTS_STATUS": {

      const newState: EventsState = action.payload;

      return {

        ...reducerState,

        state: newState,

      };

    }

    case "LOAD_CALENDAR_GUIDANCE_EVENTS": {

      const newEvents: CalendarEvent[] = action.payload;

      const newEventsFiltered = newEvents.filter((event) =>

        evaluateEvents(event, reducerState.guidanceEvents)

      );



      return {

        ...reducerState,

        guidanceEvents: [...reducerState.guidanceEvents, ...newEventsFiltered],

      };

    }

    case "ADD_CALENDAR_GUIDANCE_EVENT": {

      const newEvent: CalendarEvent[] = [action.payload];

      return {

        ...reducerState,

        guidanceEvents: [...reducerState.guidanceEvents, ...newEvent],

      };

    }

    case "UPDATE_CALENDAR_GUIDANCE_EVENT": {

      const updateEvent: CalendarEvent[] = [action.payload];

      const filteredState = reducerState.guidanceEvents.filter(

        (event) => event.id !== action.payload.id

      );



      return {

        ...reducerState,

        guidanceEvents: [...filteredState, ...updateEvent],

      };

    }

    case "DELETE_CALENDAR_GUIDANCE_EVENT": {

      if (typeof action.payload === "number") {

        return {

          ...reducerState,

          guidanceEvents: reducerState.guidanceEvents.filter(

            (event: CalendarEvent) => event.id !== (action.payload as number)

          ),

        };

      }

      const guidanceEvents = reducerState.guidanceEvents;

      const currentEventObject = action.payload as CalendarEvent;

      const currentEventIndex = guidanceEvents.findIndex(

        (event) => event.id === currentEventObject.id

      );

      guidanceEvents[currentEventIndex] = currentEventObject;



      return {

        ...reducerState,

        guidanceEvents: guidanceEvents,

      };

    }

    default:

      return reducerState;

  }
```

2022-03-31 09:03 UTC, TeroOtavia requested changes

2022-03-31 09:03 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/study-history.tsx
> +      </NavigationElement>
No need to use binds because functional component

2022-04-04 08:21 UTC, TeroOtavia submitted a review, later dismissed

2022-04-04 12:26 UTC, jjlankinen submitted a review, later dismissed
This has been approved

2022-04-05 09:18 UTC, jjlankinen approved these changes
Re-approving stale review

2022-04-05 09:18 UTC, merged