5589 perusopetuksen hops lomake muikkuun v2
otavanopisto/muikku pull request #6145
Opened 2022-06-08 06:06 UTC by TeroOtavia

Added compulsory education hops. Includes big changes to guider and studies views like new hops view with planning tools and tool to view compulsory education study proggress.

Resolves: #5589

2022-06-09 05:48 UTC, pkukkon requested changes

2022-06-09 05:48 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspacecopywizard/WorkspaceCopyWizardJsPluginMessages_en.properties
> +plugin.workspacecopywizard.materialCopyType.label How materials are copied
Missing equal sign between key and value

2022-06-09 05:48 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspacecopywizard/WorkspaceCopyWizardJsPluginMessages_fi.properties
> +plugin.workspacecopywizard.materialCopyType.label Materiaalien kopiointi tapa
Missing equal sign between key and value. Same with the key above this.

2022-06-09 05:48 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +      userEntityController.setUserEntityProperty(userEntity, payload.getKey(), payload.getValue());
If the currently logged in user is a student, the user entity id in the payload must match the logged user entity id.

2022-06-09 05:48 UTC, pkukkon commented on updates/1.120/210924_hops.xml
> +  <sql>drop index ind_hsug_suggestion on hopsSuggestion;</sql>
Why first create an index to a table and then immediately drop it?

2022-06-09 05:48 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesController.java
> +  public Note updateArchived(Note note) {
Code would be more readable if method name was toggleArchived.

2022-06-09 05:48 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +  @Path ("/note/{NOTEID}/archive")
Seemingly this endpoint is used to both archive and unarchive notes? If so, code would be more readable if the path (and method name) was toggleArchived or something.

2022-06-09 05:48 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +          if (loggedUserRole.equals(EnvironmentRoleArchetype.STUDENT)) {
Wouldn't it be shorter to just say...

`if (loggedUserRole.equals(EnvironmentRoleArchetype.STUDENT) || !creatorUserRole.equals(EnvironmentRoleArchetype.STUDENT))`

Same with the else block below.

2022-06-09 05:48 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
>    @RESTPermit(handling = Handling.INLINE)
Method assumes caller is logged in, so the annotation should be...

`@RESTPermit (handling = Handling.INLINE, requireLoggedIn = true)`

Check other methods of this service as well.

2022-06-09 10:37 UTC, aviljakaine requested changes

2022-06-09 10:37 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
> +    if(!hopsController.isHopsAvailable(studentIdentifier)) {
Check that the logged user may create the thing?

2022-06-09 10:37 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
> +    if(!hopsController.isHopsAvailable(studentIdentifier)) {
Check that the logged user can access the thing?

2022-06-09 10:37 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
> +    if(!hopsController.isHopsAvailable(studentIdentifier)) {
Same as above

2022-06-09 10:37 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
> +    if(!hopsController.isHopsAvailable(studentIdentifier)) {
Same as above

2022-06-14 09:24 UTC, pkukkon submitted a review, later dismissed
Backend assumably OK.

2022-06-14 09:50 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if(note.getArchived().equals(Boolean.FALSE)) {
Is this block useful for something? duedate=null surely isn't saved to database, it might go to the rest model though.

2022-06-15 05:23 UTC, merged