6091 kurssikaruselli
otavanopisto/muikku pull request #6154
Opened 2022-06-09 07:34 UTC by TeroOtavia

Changes:
- Added course carousel, but its currently only supported for compulsory education students
- Carousel uses basic running number order when checking what to show in carousel
- Supervisor suggestions will be also added to carousel
- Sorting order: Supervisor suggestion (alphabetical order) -> normal suggestion (alphabetical order(

2022-08-12 07:15 UTC, pkukkon requested changes

2022-08-12 07:15 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +      // If startDate is after today
Same as above.

2022-08-12 07:15 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +          // If startDate is after today
Same as above.

2022-08-12 07:15 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +      note.setStartDate(null);
Both `dueDate` and `startDate` are reset in the entity but not propagated to the database?

2022-08-12 07:15 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if (note.getArchived().equals(Boolean.TRUE)) {
Is this certainly `note` instead of `updatedNote` (could be fine - just a bit hard to read what exactly is going on).

2022-08-12 07:15 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_en.properties
> +plugin.records.descriptionDialog.title = Course description
Titles in English should always be capitalized

2022-08-12 07:15 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +      if (response.getEntity() != null) {
This null check has already been made.

2022-08-12 07:15 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +          response.getEntity().setCreatorId(toUserEntityId(response.getEntity().getCreatorId()));
This has already been done.

2022-08-12 07:15 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +          hasImage = userEntityFileController.hasProfilePicture(userEntity);
Null check `userEntity`; will crash if, for some reason, `creatorId` doesn't result in `userEntity`

2022-08-12 07:15 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +          hasImage = userEntityFileController.hasProfilePicture(userEntity);
Same as with the previous method; null checks and setting creator id done twice, `userEntity` not null checked.

2022-08-12 07:15 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +          hasImage = userEntityFileController.hasProfilePicture(userEntity);
Same as above.

2022-08-15 05:57 UTC, avukkonen approved these changes

2022-08-17 08:11 UTC, aviljakaine requested changes
Move isActive handling to toRestModel method and check the comment

2022-08-17 08:11 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if(note.getArchived().equals(Boolean.FALSE)) {
toggleArchived already sets these to null so this block shouldn't be needed here?

Also better to not change Entity's properties if there's no persist (i.e. outside a DAO).

2022-08-17 08:18 UTC, aviljakaine approved these changes

2022-08-17 09:09 UTC, merged