5598 ohjaamo ja opinnot   laksytys ja muistutukset
otavanopisto/muikku pull request #6163
Opened 2022-06-15 11:22 UTC by TeroOtavia

- Added notes functionality for students and supervisors.
- Notes can be schedule, archive, delete etc.
- Supervisor can also create notes for students

2022-08-10 10:02 UTC, avukkonen requested changes

2022-08-12 07:49 UTC, avukkonen approved these changes

2022-08-18 07:16 UTC, aviljakaine reviewed
Tiny localization fixes

2022-08-19 05:38 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_en.properties
> +plugin.records.notes.priority.high.label = high
Probably just because styling reasons

2022-08-19 05:45 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_en.properties
> +plugin.guider.user.details.proggressOfStudies = Proggress of studies
Fixed

2022-08-19 06:57 UTC, aviljakaine approved these changes

2022-08-19 07:49 UTC, avukkonen approved these changes

2022-08-19 07:58 UTC, merged