5835 arviointipyynnon perumisesta jalki arviointihistoriaan
otavanopisto/muikku pull request #6173
Opened 2022-07-14 09:05 UTC by TeroOtavia

New evaluation event type added to evaluation -> cancelled evaluation request

Resolves: #5835

2022-08-19 11:02 UTC, saaralepisto commented
https://github.com/otavanopisto/pyramus/pull/1398

2022-08-31 12:43 UTC, aviljakaine submitted a review, later dismissed

2022-09-01 04:24 UTC, pkukkon requested changes

2022-09-01 04:24 UTC, pkukkon commented on muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/model/AssessmentRequestCancellation.java
> +  private Long workspaceEntityId;
Shouldn't this be non-nullable as well?

2022-09-05 07:15 UTC, pkukkon approved these changes
Backend OK.

2022-09-05 07:53 UTC, jjlankinen approved these changes
Feature tested and works fine.

2022-09-05 07:53 UTC, merged