suggestions for users
otavanopisto/muikku pull request #6288
Opened 2022-10-14 12:03 UTC by avukkonen

Closes #6273

2022-10-17 05:03 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/continue-studies-panel.tsx
> +import Link from "../../general/link";
Unused imports

2022-10-17 05:03 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/continue-studies-panel.tsx
> +import Button from "~/components/general/button";
Unused imports

2022-10-17 05:06 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/continue-studies-panel.tsx
> +} from "~/actions/base/notifications";
These are not used anywhere. Remove imports and props and mapDispatchTopProps definings

2022-10-17 05:10 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/next-studies-panel.tsx
> +
You are passing more parameters than function can hold. There is no boolean parameter to check if user is student. If you have changed useCourseCarousel custom hook, then changes are not shown correctly

2022-10-17 05:19 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/next-studies-panel.tsx
> +const NextStudiesPanel: React.FC<NextStudiesPanelProps> = (props) => {
Is it necessary to show all suggestedWorkspace here? Wouldn't student counselors suggestion be enough. Like suggested for next and/or suggested for optional?

As now we are loading same big chunk of data for two places, for Studies view and now for this. If we are ruling that enviroment frontpage only gives sneak peaks or most important bits of data, then I would say this is overkill.

2022-10-17 05:21 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/next-studies-panel.tsx
> +  lastWorkspace: WorkspaceMaterialReferenceType;
Is not used anywhere, remove prop and mapStateToProps definings

2022-10-19 10:28 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/next-studies-panel.tsx
> +import { useCourseCarousel } from "~/components/general/carousel/hooks/use-course-carousel";
Unused import

2022-10-19 10:31 UTC, TeroOtavia requested changes
Fix imports and then its ready to merge

2022-10-20 08:30 UTC, jjlankinen submitted a review, later dismissed
Tested manually UI and feature wise and works as it should. 

Possible other code reviews still needed to be apporved before merge.

2022-10-21 08:06 UTC, TeroOtavia submitted a review, later dismissed

2022-10-24 04:27 UTC, jjlankinen approved these changes
Approved twice.

2022-10-24 04:28 UTC, merged