6247 journal as a new assignment type
otavanopisto/muikku pull request #6291
Opened 2022-10-19 10:35 UTC by TeroOtavia

Material has now new page type (JOURNAL). With that and with new Ckeditor field (JournalField) users can create "mandatory" journal assignments to material. When students writes something to that field its automatically creates new journal entry to journal view also.

Resolves: #6247

2022-11-01 07:59 UTC, pkukkon requested changes
Minor backend cleanup work. CKEditor plugin seems OK.

2022-11-01 07:59 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/QueryJournalFieldController.java
> +  public QueryJournalField findQueryTextFieldByMaterialAndName(Material material, String name) {
findQueryJournalFieldByMaterialAndName

2022-11-01 07:59 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialFieldAnswerController.java
> +  /* JournalField */
Are these three methods used at all? Doesn't WorkspaceJournalFieldIOHandler create, update, and find field data via WorkspaceJournalController?

2022-11-01 07:59 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/WorkspaceJournalFieldIOHandler.java
> +        journalEntry = workspaceJournalController.updateJournalEntry(journalEntry, field.getWorkspaceMaterial().getTitle(), value);
For title, maybe use journalEntry.getTitle() instead? If the entry exists and the user edited its title in the journal, that title wouldn't then revert back to page title if the user edits the entry in materials.

2022-11-01 07:59 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/WorkspaceJournalFieldIOHandler.java
> +    } else {
Is this if..else block needed? Even if the value would be blank, shouldn't it still lead to a journal entry being either created or updated?

2022-11-01 08:24 UTC, aviljakaine commented on updates/1.124/221006_journalEntry.xml
> +  <sql>alter table workspaceJournalEntry add column materialFieldReplyIdentifier varchar(255) after created;</sql>
Could capitalize the W in table name (another case on the next line), some database instances are case sensitive.

2022-11-02 06:57 UTC, avukkonen requested changes

2022-11-02 07:03 UTC, pkukkon approved these changes
Backend OK.

2022-11-02 07:20 UTC, avukkonen approved these changes

2022-11-02 07:21 UTC, merged