6340 change frontend language picker to use rest
otavanopisto/muikku pull request #6352
Opened 2022-11-16 06:02 UTC by TeroOtavia

Changes:
- changing localization is done by using mApi endpoint and any related unnecessesary jsf files are removed
- couple meta tags are also moved to whoami endpoint as part of moving towards separating frontend and backend

2022-11-18 07:19 UTC, pkukkon requested changes

2022-11-18 07:19 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/me/MeRESTService.java
> +    String lang = (locale == null || locale.getLanguage() == null) ? "FI" : locale.getLanguage().toUpperCase();
Shouldn't this be lowercase to indicate language? After all, only country names are in uppercase (e.g. `en-GB` or `en-US`)

2022-11-18 08:48 UTC, pkukkon submitted a review, later dismissed
Backend OK.

2022-11-21 09:23 UTC, avukkonen approved these changes

2022-11-21 12:51 UTC, merged