4595 interim evaluation
otavanopisto/muikku pull request #6362
Opened 2022-11-16 12:35 UTC by TeroOtavia

- Added new assignmentType option, interim evaluation. This allows to create interim evaluation request from material side directly.
- Changes to evaluation that adds functionalities to handle interim evaluation requests
- Student records also can show possible interim requests and evaluations for every course included there
- Includes any necessary styling

2022-11-17 05:29 UTC, pkukkon commented
- resolves #4595
- fixes #6345 
- fixes #6346 
- fixes #6347 
- fixes #6348 
- fixes #6349 
- fixes #6350

2022-11-21 07:03 UTC, aviljakaine submitted a review, later dismissed

2022-11-21 07:47 UTC, avukkonen requested changes

2022-11-21 07:47 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-event-content-card.tsx
>        default:
Why the fragments?

2022-11-21 08:03 UTC, avukkonen submitted a review, later dismissed

2022-11-21 08:29 UTC, aviljakaine approved these changes

2022-11-22 06:37 UTC, avukkonen approved these changes

2022-11-22 06:45 UTC, merged