6333 oppimispaivakirjan kokonaispalaute
otavanopisto/muikku pull request #6371
Opened 2022-11-18 12:11 UTC by TeroOtavia

Added functionality to give feedback for course journals. 

This includes changes to:
-  evaluation, teachers can give, update and delete course journal feedback
- workspace journals, students can read course journal feedback
- studies records, students can read course journal feedback from here by workspace if they don't have access anymore to actual workspace of that specific course

Other changes:
- studies records now also have journal comments if exists

Resolves: #6333

2022-11-21 10:51 UTC, avukkonen requested changes

2022-12-09 08:21 UTC, avukkonen approved these changes

2022-12-09 08:37 UTC, pkukkon requested changes
Backend changes

2022-12-09 08:37 UTC, pkukkon commented on muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/model/WorkspaceJournalFeedback.java
> +  public void setId(Long id) {
No setter for id, just in case.

2022-12-09 08:37 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
> +  private SchoolDataBridgeSessionController schoolDataBridgeSessionController;
Not needed.

2022-12-09 08:37 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
> +    if (creatorEntity != null) {
Users' names can be resolved faster via...

`userEntityController.getName(userEntity)`

2022-12-09 08:37 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
> +plugin.workspace.journal.feedback.notification.delete.error = P�iv�kirjakokonaispalautteen lataus ep�onnistui
Oppimispäiväkirjan kokonaispalautteen lataus epäonnistui

2022-12-09 08:37 UTC, pkukkon commented on updates/1.125/221108_journalFeedback.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Database version 1.125 already claimed in devel.

2022-12-13 05:42 UTC, pkukkon approved these changes
Backend seems okay, although database version has to be double-checked before turning this into a pull request.

2023-01-16 11:29 UTC, pkukkon commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_fi.properties
> +plugin.records.journal.comments.title = Kommentit
Line mismatch between bundles (English bundle has an empty line at line 20)

2023-01-16 11:30 UTC, pkukkon commented on updates/1.126/221108_journalFeedback.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Just a reminder to double-check database version number before merging into devel (currently OK).

2023-01-27 06:46 UTC, avukkonen approved these changes

2023-01-27 06:51 UTC, pkukkon approved these changes

2023-01-27 07:09 UTC, avukkonen requested changes

2023-01-27 07:09 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/hooks/useJournals.ts
> +            const journalFeedback = <WorkspaceJournalFeedback>(
Should there be try catch block here with error hangdling?

2023-01-27 07:28 UTC, avukkonen submitted a review, later dismissed

2023-01-27 07:28 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/hooks/useJournals.ts
>              const journals = <WorkspaceJournalType[]>await promisify(
should there be try-catch with error handling?

2023-01-27 07:43 UTC, aviljakaine approved these changes
ind_jfee_workspace_student should be declared in WorkspaceJournalFeedback but this can be done in separate pr

2023-01-27 08:16 UTC, pkukkon submitted a review, later dismissed

2023-01-27 09:01 UTC, aviljakaine approved these changes
woodstamp

2023-01-27 10:12 UTC, merged