5091 lang attribuutti
otavanopisto/muikku pull request #6429
Opened 2022-12-22 06:53 UTC by TeroOtavia

- Added lang attribute to workspace description
- Added lang attribute to workspace materials
- Added lang attribute to material editor
- Added lang attribute to material loader components
- Added lang attribute to content topic and element
- Lang attribute by default comes from workspace settings which defaults
to "fi" if not set.
- Lang attribute prioritizing order page > material > workspace

2023-02-01 13:33 UTC, aviljakaine reviewed
Conflicts need to be fixed.
Backend seems ok if the null valued parameters are checked to be as desired.

2023-02-01 13:33 UTC, aviljakaine commented on muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties
> +plugin.workspace.materialsManagement.editorView.subTitle.localeCode = Locale code
Lines mismatch with the fi locale

2023-02-02 07:10 UTC, aviljakaine approved these changes
Backend ok

2023-02-02 07:36 UTC, pkukkon requested changes

2023-02-02 07:36 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
> +          false, workspaceFolder.getLanguage() == null ? null : workspaceFolder.getLanguage());
Could simply say `workspaceFolder.getLanguage()`

2023-02-02 07:36 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
> +    if (payload.getLanguage() != null && !workspaceEntity.getLanguage().equals(payload.getLanguage())) {
NPE chance if workspace entity language is null

2023-02-02 07:36 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceSystemRESTService.java
> +        WorkspaceFolder helpSection = workspaceMaterialController.createWorkspaceFolder(helpRoot, "Suoritusohjeet", "suoritusohjeet", null);
`WorkspaceLanguage.fi`

2023-02-02 07:36 UTC, pkukkon commented on updates/1.127/221212_Lang_attribute.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Needs version bump

2023-02-02 07:46 UTC, pkukkon approved these changes

2023-02-02 07:55 UTC, aviljakaine approved these changes
Backend ok

2023-02-06 11:45 UTC, avukkonen approved these changes

2023-02-06 11:59 UTC, merged