Työtilan käyttäjälistauksen aakkosjärjestys
otavanopisto/muikku pull request #6486
Opened 2023-02-14 07:36 UTC by saaralepisto

closes #5815

2023-02-14 08:49 UTC, aviljakaine approved these changes
Should be tested thoroughly but code review wise ok.

2023-02-15 06:23 UTC, pkukkon requested changes

2023-02-15 06:23 UTC, pkukkon commented on muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
> +      System.out.println(query.toString());
Debug code

2023-02-15 12:28 UTC, pkukkon approved these changes

2023-02-16 11:00 UTC, aviljakaine approved these changes

2023-02-16 11:01 UTC, merged