6433 readspeaker web reader implementation
otavanopisto/muikku pull request #6516
Opened 2023-03-08 06:20 UTC by TeroOtavia

Readspeaker webReader is now implemented to Muikku. It is only currently used in the workspace materials. For this use case, everything in the materials like material loader is configurated to work with webReader. Most of the material fields are skipped and so on...

Resolves: #6433

2023-05-22 11:34 UTC, avukkonen requested changes

2023-05-22 11:34 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
> +            <ReadspeakerMessage text="Valintakenttä" />
TODO: lokaalit

2023-05-22 11:34 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
> +          <ReadspeakerMessage text="Valintakenttä" />
TODO: lokaalit

2023-05-22 11:34 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx
> +        <ReadspeakerMessage text="Tekstikenttä" />
TODO: localization

2023-05-22 11:34 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/mathjax.tsx
> +          <ReadspeakerMessage text="Matikkakaava" />
TODO : localization

2023-05-24 09:44 UTC, avukkonen submitted a review, later dismissed

2023-05-25 09:33 UTC, avukkonen submitted a review, later dismissed

2023-05-25 09:38 UTC, avukkonen approved these changes

2023-06-01 10:09 UTC, jjlankinen approved these changes
Questionable approve but PR is tested quite well. Further testing will be done in demo server after the merge.

2023-06-01 10:09 UTC, merged