6501 pedagogical support form implementation
otavanopisto/muikku pull request #6528
Opened 2023-03-21 11:18 UTC by TeroOtavia

Pedagogical support form for uppersecondary student. This pr includes new custom made wizard component with all its own functionalities and other subcomponetns etc. It is also used by this new form. 

Pyramus 1448 branch is needed

Resolves: #6501

2023-05-17 09:48 UTC, aviljakaine requested changes
- package.json hats off
- redo package-lock.json
- check if the exposed contactinfo is appropriate

2023-05-17 09:48 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyRestService.java
> +          contactInfo = userController.getUserContactInfo(userEntity.getDefaultSchoolDataSource().getIdentifier(), userEntity.getDefaultIdentifier());
Does the form really need all this information about the creator/owner (birthday, address, phone email etc)? Especially if the creator/owner can be a staff member.

2023-05-26 06:16 UTC, avukkonen approved these changes

2023-05-29 08:01 UTC, aviljakaine submitted a review, later dismissed
One question about access check, if not needed, backend is ok

2023-05-29 08:18 UTC, aviljakaine approved these changes

2023-05-31 06:39 UTC, jjlankinen approved these changes
Re-approving frontend changes on behalf of a another member

2023-05-31 06:41 UTC, merged