Ceepos payments Nettiperuskoulu support
otavanopisto/muikku pull request #6531
Opened 2023-03-24 06:20 UTC by pkukkon

- resolves #6472
- needs product code configuration

2023-03-27 06:14 UTC, aviljakaine reviewed
Backend ok

2023-04-20 08:11 UTC, saaralepisto submitted a review, later dismissed

2023-04-20 08:35 UTC, aviljakaine submitted a review, later dismissed

2023-04-21 10:28 UTC, TeroOtavia requested changes

2023-04-21 10:28 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
> +      //}
These could be removed if not needed

2023-04-21 10:40 UTC, TeroOtavia approved these changes

2023-04-21 11:38 UTC, merged