6546 contact info and extra functionality popover
otavanopisto/muikku pull request #6563
Opened 2023-05-05 09:33 UTC by TeroOtavia

Info popover to show data when hovering activator element (Example recipient/sender name in communicator). Branch also ads nameExtension to workspace name that is either showed as recipient.

Resolves: #6546 
Resolves: #6555

2023-05-17 08:31 UTC, avukkonen submitted a review, later dismissed

2023-05-22 07:12 UTC, pkukkon requested changes

2023-05-22 08:00 UTC, aviljakaine requested changes
`loggedUserHasPermission` could've maybe been named better to indicate what it means :D

2023-05-22 08:57 UTC, avukkonen requested changes

2023-05-22 08:57 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/guider-link.tsx
> +      aria-label="Avaa opiskelijan ohjausnäkymä"
Todo: lokalisointi

2023-05-25 09:04 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
> -
The whole file can be reset to HEAD if it's just linebreaks. Same with `UserSchoolDataBridge` and `PyramusUserSchoolDataBridge`

2023-05-25 09:10 UTC, pkukkon commented on muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
> +        if (d.equals(UserInfo.EMAIL)) {
Student vs. student resolves to 403 earlier, so this scenario shouldn't happen.

2023-05-25 09:17 UTC, pkukkon requested changes

2023-05-25 09:18 UTC, pkukkon requested changes
Some minor logic changes based on the unresolved comments.

2023-05-29 06:52 UTC, pkukkon approved these changes

2023-05-29 08:47 UTC, aviljakaine approved these changes

2023-05-29 10:35 UTC, merged