6542 muistiinpanot uuden merkinnan sijainti
otavanopisto/muikku pull request #6566
Opened 2023-05-08 11:10 UTC by TeroOtavia

In the notebook when creating new note position can be selected from the list below and default place to create note can be selected from dropdown list.

Resolves: #6542

2023-05-16 12:27 UTC, avukkonen requested changes

2023-05-25 10:01 UTC, avukkonen submitted a review, later dismissed

2023-05-26 06:53 UTC, aviljakaine submitted a review, later dismissed
Backend ok

2023-05-26 09:33 UTC, aviljakaine submitted a review, later dismissed
Backend seems still ok

2023-05-26 09:35 UTC, pkukkon submitted a review, later dismissed

2023-05-26 09:45 UTC, pkukkon approved these changes

2023-05-26 11:13 UTC, avukkonen approved these changes

2023-05-26 11:13 UTC, avukkonen approved these changes

2023-05-26 11:13 UTC, merged