6569 uppersecondary school study progress table
otavanopisto/muikku pull request #6625
Opened 2023-08-10 06:57 UTC by TeroOtavia

Newly refactored study progress table and list. It works now also with uppersecondary students. Also includes chance to supervisors to apply to workspace behalf of student.

Needs pyramus 6546

Resolves: #6569

2023-08-16 11:34 UTC, jjlankinen requested changes
Via manual testing for Nettilukio student backend crashes to NPE in records view, needs to be fixed.

Caused by: java.lang.NullPointerException: Cannot read the array length because "results" is null

2023-08-17 05:57 UTC, jjlankinen approved these changes

2023-08-30 08:18 UTC, aviljakaine requested changes

2023-08-30 08:18 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    String studentLink = String.format("<a href=\"%s/guider#userprofile/%s\" >%s</a>", baseUrl, studentIdentifier.toId(), userName);
Does this mean that the student also gets a link to guider (which they cannot access)? Student seems to be in the recipient list at least.

2023-08-30 09:13 UTC, pkukkon requested changes
Backend changes

2023-08-30 09:13 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    User loggedUser = userController.findUserByUserEntityDefaults(sessionController.getLoggedUserEntity());
No need to fetch logged user all the way from Pyramus just to determine their name. Use `userEntityController.getName` instead.

2023-08-30 09:13 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    UserEntity studentEntity = userEntityController.findUserEntityByDataSourceAndIdentifier(studentIdentifier.getDataSource(), studentIdentifier.getIdentifier());
Could be just `userEntityController.findUserEntityByUserIdentifier(studentIdentifier)`

2023-08-30 09:13 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    UserSchoolDataIdentifier userSchoolDataIdentifier = userSchoolDataIdentifierController.findUserSchoolDataIdentifierBySchoolDataIdentifier(studentIdentifier);
Why do you need this?

2023-08-30 09:13 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    workspaceController.createWorkspaceUserSignup(workspaceEntity, userSchoolDataIdentifier.getUserEntity(), new Date(), entity.getMessage());
Why `userSchoolDataIdentifier.getUserEntity()`? Didn't you already figure out `studentEntity` towards the very beginning of the method?

2023-08-30 09:13 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +        throw new RuntimeException(String.format("Search provider couldn't find a unique workspace. %d results.", searchResult.getTotalHitCount()));
Do not throw runtime exceptions in endpoints. Replace with something like `return Response.status(Status.INTERNAL_SERVER_ERROR).entity("yaddayaddayadda").build();`

2023-08-30 09:13 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +      throw new RuntimeException(String.format("Elastic search provider not found.", searchProvider));
Same as above.

2023-09-01 09:05 UTC, saaralepisto commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +        if (result.contains(",")) {
A student can have several choices in one subject and in that case it will be saved as a comma-delimited value.

2023-09-04 10:57 UTC, pkukkon requested changes
Some backend changes.

2023-09-04 10:57 UTC, pkukkon commented on muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/workspace/WorkspaceRestMessages_en.properties
> +rest.workspace.joinWorkspace.joinNotification.counselor.caption = Staff member {0} has joined student {1} workspace {2}
Line four still unchanged.

2023-09-04 11:05 UTC, aviljakaine requested changes
Just a small status change

2023-09-04 11:05 UTC, pkukkon commented on muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/workspace/WorkspaceRestMessages_fi.properties
> +rest.workspace.joinWorkspace.joinNotification.counselor.caption = Henkil�kunnan j�sen {0} on ilmoittanut opiskelijan {1} kurssille {2}
Tämä voisi muuten olla ihan vaan...

`{0} on ilmoittanut opiskelijan {1} kurssille {2}`

Lisäksi opiskelijalle voisi väsätä astetta tuttavallisemman variaation...

`{0} ilmoitti sinut kurssille {1}`

2023-09-07 04:56 UTC, pkukkon approved these changes
Backend OK (if issues in the Google Drive document have also been addressed).

2023-09-07 05:55 UTC, aviljakaine submitted a review, later dismissed
Backend ok

2023-12-19 08:03 UTC, pkukkon requested changes
- Database version 1.141 already claimed
- Why are there changes in timed notifications projects?
- Why has mvn.log been committed?
- Why have plenty of node_modules been committed?

2023-12-20 06:10 UTC, pkukkon requested changes
Some backend changes.

2023-12-20 06:10 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +    String loggedUserName = loggedUserEntityName.getDisplayName();
Why move this to a separate variable? Places where this is used could simply say `loggedUserEntityName.getDisplayName()` anyway.

2023-12-20 06:10 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/HopsController.java
> +      if (userSchoolDataIdentifier != null && (userSchoolDataIdentifier.hasRole(EnvironmentRoleArchetype.ADMINISTRATOR) || userSchoolDataIdentifier.hasRole(EnvironmentRoleArchetype.MANAGER) || userSc
Use `userSchoolDataIdentifier.hasAnyRole` instead.

2023-12-20 06:10 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
> +    Boolean studentCurriculumOPS2021 = curriculumName != null && curriculumName.equals("OPS 2021");
`StringUtils.equalsIgnoreCase(curriculumName, "ops 2021")`

2023-12-20 06:10 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
> +              Workspace workspace = workspaceController.findWorkspace(workspaceEntity);
Add a TODO here. We have to fetch workspace from Pyramus to fetch workspace type from Pyramus. Adding workspace type to Elastic would eliminate the need for both calls. This change is too big to implement in this PR but should be refactored later in order to improve performance.

2023-12-20 06:10 UTC, pkukkon commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +    results =  pyramusClient.get(String.format("/students/students/%d/subjectChoices", studentId), String[].class);
Why not `String results[] = pyramusClient.get` instead?

2023-12-21 08:24 UTC, pkukkon approved these changes
Backend seems OK.

2024-01-08 07:37 UTC, aviljakaine approved these changes

2024-01-08 10:01 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/study-progress/hooks/useSuggestedList.ts
> +          setSuggestins((suggestions) => ({
setSuggestions

2024-01-08 10:41 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +  "studymatrix": {
studyMatrix

2024-01-08 10:42 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +      "signUpError": "Opiskelijan ilmoittaminen työtilaan epäonnistui"
```suggestion
      "signUpError": "Opiskelijan ilmoittaminen kurssille epäonnistui"
```

2024-01-08 10:42 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +      "signUpStudentToWorkspace": "Ilmoita opiskelija työtilaan {{workspaceName}}",
```suggestion
      "signUpStudentToWorkspace": "Ilmoita opiskelija kurssille {{workspaceName}}",
```

2024-01-08 10:42 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +      "signUpStudent": "Ilmoita opiskelija työtilaan",
```suggestion
      "signUpStudent": "Ilmoita opiskelija kurssille",
```

2024-01-08 10:43 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +      "signupStudentToWorkspace": "Ilmoita työtilaan",
```suggestion
      "signupStudentToWorkspace": "Ilmoita kurssille",
```

2024-01-08 10:44 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "signUpStudent": "Sign up student to workspace",
```suggestion
      "signUpStudent": "Sign up student to course",
```

2024-01-08 10:45 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "signUpError": "Signing up to course failed"
```suggestion
      "signUpStudent": "Sign up student to workspace",
      "signUpStudentToWorkspace": "Sign up student to course {{workspaceName}}",
      "transfered": "Transfered",
      "transferedLanguages": "Transfered: Languages",
      "transferedOther": "Transfered: Other",
      "transferedSkillAndArt": "Transfered: Skill and art"
    },
    "notifications": {
      "signUpError": "Signing up to course failed"
```

2024-01-08 10:45 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "signUpStudentToWorkspace": "Sign up student to workspace {{workspaceName}}",
```suggestion
      "signUpStudentToWorkspace": "Sign up student to course {{workspaceName}}",
```

2024-01-08 11:39 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +      "transfered": "Hyväksiluettu",
transferred kaikkiin

```suggestion
      "transferred": "Hyväksiluettu",
```

2024-01-08 11:40 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
> +      "inprogress": "Kesken",
```suggestion
      "inProgress": "Kesken",
```

2024-01-08 11:54 UTC, avukkonen requested changes
Pieniä muutoksia tarvitsisi

2024-01-09 06:25 UTC, avukkonen approved these changes

2024-01-09 08:06 UTC, merged