Log material modifications that leads to answers being removed
otavanopisto/muikku pull request #6640
Opened 2023-08-25 07:49 UTC by pkukkon

- resolves #6638

2023-09-04 07:39 UTC, aviljakaine submitted a review, later dismissed

2023-09-05 06:37 UTC, TeroOtavia requested changes

2023-09-05 06:37 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts
> +        }
Is this try catch block needed? It doesn't have any effect to anything at the moment

2023-09-05 06:37 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts
> +import { ServerResponse } from "http";
Unused import

2023-10-05 09:45 UTC, jjlankinen approved these changes
REquested cxhanges and conflicts has been fixed.

2023-10-05 09:47 UTC, TeroOtavia approved these changes

2023-10-05 10:01 UTC, merged