Tieto pedagogisen tuen suunnitelman olemassaolosta opiskelijan tietoihin
otavanopisto/muikku pull request #6764
Opened 2023-10-12 06:06 UTC by saaralepisto

closes #6664

2023-10-12 10:27 UTC, pkukkon requested changes

2023-10-12 10:27 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
> +  private Boolean getHasPedagogyForm(String studentIdentifier) {
This method seems to have been copy/pasted to several classes. Couldn't we simply have...

```
public boolean hasPedagogyForm(String studentIdentifier) {
  return findFormByStudentIdentifier(studentIdentifier) != null;
}

```
...in `PedagogyController` instead?

2023-10-12 10:27 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java
> +            null));
I'd prefer `Boolean.FALSE` over `null`, when dealing with boolean values. Same comment applies to multiple classes in this PR.

2023-10-12 10:58 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/PedagogyController.java
> +  public Boolean getHasPedagogyForm(String studentIdentifier) {
I'd still like to see this optimized as...

```
public boolean hasPedagogyForm(String studentIdentifier) {
  return findFormByStudentIdentifier(studentIdentifier) != null;
}
```

so Java doesn't have to create variables that are immediately garbage collected after leaving this method.

2023-10-12 11:22 UTC, pkukkon approved these changes
Backend OK.

2023-11-03 11:30 UTC, avukkonen approved these changes

2023-11-03 11:31 UTC, merged