6849 dialog component with focus trap and other accessiblity functionality
otavanopisto/muikku pull request #6853
Opened 2023-10-27 09:06 UTC by TeroOtavia

Changes:
- Focus trap added to Dialog component
- close link replaced with Iconbutton
- some aria label refactoring (checked using axe chrome extension)

Resolves: #6849

2023-12-05 08:46 UTC, jjlankinen requested changes
Problems that UI tests caught will not be fixed until FocusTrap related issues are solved.

2023-12-05 08:46 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
> +            <FocusTrap active={this.state.visible}>
FocusTrap prevents second dialog from opening which is used when creating a new purchase for study time period increase.

Problem might be somewhat related to UX/UI design also as I think opening dialog within a dialog is a bit questionable and always harder to handle accessibility wised. Currently there's nothing to be done about it and FocusTrap needs to be reworked to support this functionality but in the future I think we should avoid this kind of thing.

2023-12-10 16:04 UTC, avukkonen approved these changes

2024-03-04 08:54 UTC, jjlankinen approved these changes

2024-03-04 08:54 UTC, merged