Form changed done
otavanopisto/muikku pull request #6962
Opened 2024-02-13 12:48 UTC by TeroOtavia

Form changed:
- Pedagogisen tuen perusteet select field replaved with Tuen tarve textarea

Resolves: #6902

2024-03-01 08:35 UTC, avukkonen requested changes

2024-03-01 08:35 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-PDF.tsx
> +          <Text style={styles.infoFieldLabel}>Tuen tarve</Text>
Lokalisointi

2024-03-01 08:35 UTC, avukkonen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/need-of-support-information.tsx
> +              label="Tuen tarve"
Lokalisointi

2024-03-04 09:49 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/steps/need-of-support-information.tsx
> +              label="Tuen tarve"
Korjattu.

2024-03-04 09:49 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/pedagogy-PDF.tsx
> +          <Text style={styles.infoFieldLabel}>Tuen tarve</Text>
Korjattu.

2024-03-04 09:51 UTC, avukkonen approved these changes

2024-03-04 11:13 UTC, merged