Slice: Tietojen haku pyramuksesta
otavanopisto/muikku pull request #7018
Opened 2024-03-21 04:57 UTC by saaralepisto

closes #6957

2024-03-21 05:01 UTC, saaralepisto commented
https://github.com/otavanopisto/pyramus/pull/1559

2024-03-26 08:01 UTC, pkukkon requested changes
Minor changes.

2024-03-26 08:01 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/studentcard/StudentCardRESTService.java
> +    if (!SchoolDataIdentifier.fromId(studentIdentifier).equals(sessionController.getLoggedUser()) && !sessionController.hasRole(EnvironmentRoleArchetype.STUDENT)) {
`SchoolDataIdentifier.fromId` already done on the previous line.

2024-05-29 07:26 UTC, aviljakaine reviewed
Ok, pieni ei-kriittinen muutos, jos luppoaikaa

2024-05-29 07:26 UTC, aviljakaine commented on muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
> +  public BridgeResponse<fi.otavanopisto.muikku.schooldata.payload.StudentCardRESTModel> updateActive(String studentIdentifier, StudentCardRESTModel payload, Boolean active) {
`payload` ei taida olla käytössä täällä, voisi ehkä poistaa tästä ja rajapinnasta, mutta ei kriittinen

2024-06-04 09:11 UTC, aviljakaine approved these changes

2024-06-04 11:54 UTC, pkukkon approved these changes
Backend OK.

2024-06-05 08:28 UTC, merged