6833 wcag 1.1.1, 2.1.1 ja 4.1.2.  suoritukset valilehdella on useita saavutettavuusongelmia
otavanopisto/muikku pull request #7025
Opened 2024-03-27 11:21 UTC by TeroOtavia

Studies records list accessibility rework:
- record items have now keyboard support (space + enter will expand/shrink record info)
- record activity indicator is now focusable and opens info when focus is active
- added aria attributes where they are necessary

Resolves: #6833

2024-04-03 09:45 UTC, jjlankinen requested changes

2024-04-03 09:45 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "evaluableActivity": "Arvioitavia tehtäviä tehty {{percent}}%",
EN locales missing in lines 495 and 496 and might be good to change the keys also to be more inline with our terminology.
```
"exercisesActivity": "Exercises done {{percent}}%",
"assignmentsActivity": "Assignments done {{percent}}%",
```

2024-04-05 09:24 UTC, jjlankinen requested changes

2024-04-05 09:24 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "evaluableDonePercent": "Assignments done {{percent}}%",
`"evaluableDonePercent": "Assignments done {{percent}}%",`

muutetaan edelleen muotoon:

`"assignmentsActivity": "Assignments done {{percent}}%",`

Eli käytetään assignment termiä ennemin kuin keksittyä evaluable termiä (ei ole oikea sana).

2024-04-05 09:24 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "excersiseDonePercent": "Excersises done {{percent}}%",
`"excersiseDonePercent": "Excersises done {{percent}}%",`

muutetaan edelleen muotoon:

`"exercisesActivity": "Exercises done {{percent}}%",`

Eli korjataan nyt typot heti.

2024-04-08 09:49 UTC, avukkonen approved these changes

2024-04-16 05:56 UTC, jjlankinen requested changes

2024-04-16 05:56 UTC, jjlankinen commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
> +      "exercisesActivity": "Excersises done {{percent}}%",
Fix the typo: `Excersises done` -> `Exercises done`

2024-04-16 07:04 UTC, jjlankinen approved these changes

2024-05-14 07:12 UTC, merged