7033 signup message
otavanopisto/muikku pull request #7055
Opened 2024-05-06 08:56 UTC by TeroOtavia

Changes:
- Workspace can now have custom signup message
- Workspace signup groups can have now custom signup message that exceeds workspace signup message if it was set.
- Workspace management refactored to be function component with multiple sub components to decrease re-rendering when state updates.
- Workspace permissions aka "signup groups" are now updated with one api call. This also prevents permission list to suffle items between updates.

Resolves: #7033

2024-05-07 05:58 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
> +        : new WorkspaceSignupMessageRestModel(false, "", "");
There were some front end issues with this and it was requested as empty strings for front end purposes. We did discuss if some other response code would've been more correct when the message doesn't yet exist. Ended up with this though.

2024-05-07 05:59 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
> +    if (payload == null || StringUtils.isAnyBlank(payload.getCaption(), payload.getContent())) {
No way to remove one, they can always be disabled though.

2024-05-07 08:27 UTC, aviljakaine commented
> Couple of generic comments, and the course signup test might need adjusting?

Test fixed, the sent message from course picker signup was also changed a bit as it had a weird old part to it.

2024-05-08 11:21 UTC, avukkonen requested changes

2024-05-15 10:37 UTC, avukkonen approved these changes

2024-05-22 07:59 UTC, pkukkon approved these changes
Backend OK.

2024-05-22 08:05 UTC, merged