Chat redux
otavanopisto/muikku pull request #7060
Opened 2024-05-14 07:03 UTC by TeroOtavia

Completely reworked Muikku chat:
- Muikku chat works like "discounted" Discord

New chat features:
- drag around view
- fullscreen mode
- keep count unread messages
- block users
- ui rework
- instansed discussion

2024-05-15 07:56 UTC, aviljakaine requested changes
Mainly the message sanitization should be added and some potential concurrency issues, otherwise just some small notes.

WebSocketMessenger is Singleton, it might warrant a check if it can become a hindrance in the future if the traffic increases. (Also the looping could be better with entryset iirc and the methods seem like they could be combined.) Not in scope for this PR though imo.

Shares db version with #7055

2024-05-15 07:56 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatController.java
> +      for (String sessionId : sessionIds) {
Could this have concurrency problems, the sessionIds set could be modified/iterated by two threads at the same time? Not a likely occurence for sure.

2024-05-15 07:56 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatController.java
> +      Set<Long> users = roomUsers.get(roomId);
This set might also have concurrency issues same as above.

2024-05-15 08:02 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/rest/ChatRESTService.java
> +    chatController.updateMessage(chatMessage, payload.getMessage(), sessionController.getLoggedUserEntity());
(Sanitizations could be on the controller level also.)

2024-05-16 05:14 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/rest/ChatRESTService.java
> +    if (StringUtils.isEmpty(payload.getMessage())) {
The message is always handled as plain text.

2024-05-16 05:16 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/rest/ChatRESTService.java
> +    chatController.updateMessage(chatMessage, payload.getMessage(), sessionController.getLoggedUserEntity());
Added TODO comments should messages ever be formatted in the future.

2024-05-27 07:39 UTC, avukkonen approved these changes

2024-05-28 08:15 UTC, aviljakaine approved these changes

2024-05-29 10:06 UTC, merged