7001 kurssin arviointitiedot kurssin etusivulle
otavanopisto/muikku pull request #7066
Opened 2024-05-28 04:44 UTC by avukkonen

Closes #7001

2024-09-20 06:25 UTC, TeroOtavia requested changes

2024-09-20 06:25 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/evaluation.tsx
> +   */
Some old documentation leftovers?

2024-09-23 07:54 UTC, jjlankinen approved these changes

2024-09-23 07:56 UTC, TeroOtavia approved these changes

2024-09-23 08:14 UTC, merged