Yhteydenottokirjaukset useammalle opiskelijalle kerralla
otavanopisto/muikku pull request #7116
Opened 2024-08-29 03:35 UTC by saaralepisto

closes #7101

2024-09-09 08:46 UTC, aviljakaine requested changes

2024-09-09 08:46 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/UserRecipientController.java
> +      if (roles != null) {
Tämän toiminnallisuus muuttuu aiemmasta aika paljon, etenkin vanhat communicatorin kutsut asettaa `null` roles-parametrin arvoksi. Toimiiko viestin enää?

Tekisin ehkä niin, että jos roles == null niin tarkistetaan vain isActiveUser kuten aiemmin ja muutoin sitten ladataan tuo UserSchoolDataIdentifier ja tarkistetaan rooli. Tällaisenaan jos roles == null yksikään käyttäjä ei päädy vastaanottajaksi.

2024-09-09 08:46 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/UserRecipientController.java
> +            Boolean recipientRole = hasAnyRole(roles, userSchoolDataIdentifier);
Tännekin on varmaan syytä palauttaa aiempi käsittely, jos roles == null

2024-09-09 08:46 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/UserRecipientController.java
> +    if (!CollectionUtils.isEmpty(workspaceTeacherRecipients)) {
Yhtenäisyyden vuoksi täälläkin olisi hyvä olla roolitsekki

2024-09-09 08:46 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/UserRecipientController.java
> +    if (!CollectionUtils.isEmpty(userGroupRecipients)) {
Yhtenäisyyden vuoksi täälläkin olisi hyvä olla roolitsekki

2024-09-09 08:46 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +        if (sessionController.hasPermission(GuiderPermissions.ACCESS_CONTACT_LOG, workspaceEntity))
Permission scope ei ole workspace, joten tämä ei tarkista kurssikohtaista oikeutta, vaan koko ympäristön tasolla (joka on tarkistettu jo, koska se on määritetty endpointin permissioksi). Kurssikohtainen tarkistus on kyllä hyvä ajatus, mutta siihen tarvitsee workspace-scopella olevan permission (ehkä joku olemassa oleva tai tehtävä uusi).

2024-09-09 08:46 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
> +      if (sessionController.hasEnvironmentPermission(GuiderPermissions.ACCESS_CONTACT_LOG)) {
Sama permissio tsekattu kuin mikä tsekataan endpointtiin tullessa. Eli ehkä turha tässä tilanteessa, ellei tarkoituksena ole antaa joillekin rooleille mahdollisuus lähettää ryhmille ja toiselle roolille ei.

2024-09-19 11:05 UTC, TeroOtavia requested changes

2024-09-19 11:28 UTC, aviljakaine approved these changes
Bäkkäri mun puolesta ok

2024-09-24 07:47 UTC, TeroOtavia approved these changes

2024-09-25 06:02 UTC, merged