fixes the external view link
otavanopisto/muikku pull request #7129
Opened 2024-09-19 12:38 UTC by avukkonen

fixes #7127 
fixes #7128

2024-09-20 06:13 UTC, TeroOtavia approved these changes

2024-09-23 04:59 UTC, pkukkon requested changes

2024-09-23 04:59 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSettingsRestModel.java
> +	  this.externalViewLink = externalViewLink;
Remove tab from indentation (same with the getter)

2024-09-23 06:18 UTC, pkukkon approved these changes
Backend OK

2024-09-23 06:35 UTC, merged