Muistilappujen jatkokehitys
otavanopisto/muikku pull request #7222
Opened 2024-11-15 06:01 UTC by saaralepisto

closes #7045

2025-01-31 09:21 UTC, pkukkon requested changes

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/dao/NoteDAO.java
> +  public Note create(String title, String description, NoteType type, NotePriority priority, Long creator,
Surely newly created notes are never archived from the get-go?

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if (!note.getCreator().equals(sessionController.getLoggedUserEntity().getId())) {
Might as well put this above receiver check to not fetch data needlessly.

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +      recipientsRest.add(recipientRest);
No biggie but `recipientsRest.add(toRestModel(recipient));` to avoid temporary variables that aren't really used for anything. Multiple occurences in this class.

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    noteRestModel.setMultiUserNote(recipientsRest.size() > 1);
Once again, what function does `note.getMultiUserNote()` serve if a multi-user note depends on the number of its recipients? Multiple occurences in this class.

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +        workspaceName = workspaceController.findWorkspace(workspaceEntity).getName();
Needless Pyramus call. Use `WorkspaceEntityController.getName` instead.

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +        UserGroup usergroup = userGroupController.findUserGroup(userGroupEntity);
Needless Pyramus call. Use `UserGroupEntityController.getName` instead.

2025-01-31 09:21 UTC, pkukkon commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    return Response.ok(restModel).build();
`return Response.ok(toRestModel(updatedNoteReceiver)).build();`

2025-02-03 05:06 UTC, saaralepisto commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/dao/NoteDAO.java
> +  public Note create(String title, String description, NoteType type, NotePriority priority, Long creator,
Ei ole tarvetta luoda suoraan arkistoituna

2025-02-05 08:33 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/notes.tsx
> +const GuiderNotes = (props: GuiderNotesProps) => {
From performance perspective useCallback won't add any effect if NotesItemList is not memoized. This can be done using React.memo().

For same reason, any non primitive types needs to be memoized also. notes is already memoized by custom hook as it seems.

Note, that if this components parent re-renders also, then it won't make difference because all is re-rendered anyways. Even memoizing GuiderNotes doesn't help, as there is not any props to compare. You must evaluate if memoizing is worth to do, so if component tree is deep, calculation are expensive etc...

2025-02-05 08:38 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
> +          <NavigationTopic name={"Tila"}>
Localization

2025-02-05 08:38 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
> +          <NavigationTopic name={"Prioriteetti"}>
Localization

2025-02-05 08:48 UTC, TeroOtavia commented on muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
> +  // These are required to make the types work in the context
For readability in mind, many of this component render logic could be separated to their own render methods. Like separating students and notes view, and even NavigationTopic related section. Not mandatory, but think it.

2025-02-07 10:57 UTC, TeroOtavia approved these changes

2025-02-10 05:32 UTC, pkukkon approved these changes
Backend OK

2025-02-10 12:43 UTC, aviljakaine requested changes
DAO/Controller: jos entityn (Note/NoteRecipient) kentät on boolean, niin esim create/update-metodeissa olisi hyvä myös käyttää boolean (vs Boolean), koska null-arvoja ei näihin kaivata.

2025-02-10 12:43 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +      else { // Note creation by staff
Tsekki sallituille rooleille (student_parent ei sallittu)

2025-02-10 12:43 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if (!sessionController.hasRole(EnvironmentRoleArchetype.STUDENT)) {
student_parent ei sallittu

2025-02-10 12:43 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if (sessionController.hasRole(EnvironmentRoleArchetype.STUDENT)
Tähän ehkä voisi lisätä myös student_parent

2025-02-10 12:43 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if (sessionController.hasRole(EnvironmentRoleArchetype.STUDENT)
student_parent

2025-02-11 06:31 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
> +    if (!sessionController.hasRole(EnvironmentRoleArchetype.STUDENT) || !sessionController.hasRole(EnvironmentRoleArchetype.STUDENT_PARENT)) {
`!sessionController.hasAnyRole(STUDENT, STUDENT_PARENT)`

2025-02-11 06:32 UTC, aviljakaine commented on muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
>      if (sessionController.hasRole(EnvironmentRoleArchetype.STUDENT)
`!sessionController.hasAnyRole(STUDENT, STUDENT_PARENT)`

2025-02-11 07:19 UTC, aviljakaine approved these changes
Bäkkäri ok

2025-02-11 08:50 UTC, merged